package reversi;

import action.Action;
import action.InitBoard;
import action.Player;
import misc.Board;
import misc.Chess;
import misc.Input;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Reversi {
    private final Board board;
    private final Player X;
    private final Player O;
    private final Action initAction;
    private final Input input;

    public Reversi() {
        board = Board.createBoard(8);
        X = new Player(Chess.X);
        O = new Player(Chess.O);
        X.setOpponent(O);
        O.setOpponent(X);
        initAction = new InitBoard(X);
        input = createInput();
    }

    protected Input createInput() {
        return new Input();
    }

    public void start() {
        Action action = initAction;
        while (action != null) {
            action.performAction(this);
            action = action.getNextAction();
        }
        input.close();
    }

    public Board getBoard() {
        return board;
    }

    public Input getInput() {
        return input;
    }

    public static void main(String[] args) {
        new Reversi().start();
    }
}
